README.md
package.json
src/components/ImageViewer.vue
src/components/layers/ItkVtkLayer.vue

This PR fixes the imjoy api, itk-vtk-control UI display and add instructions for running on Mybinder.

Fix imjoy api for displaying layers

---

src/router/index.js

This PR add a `/app` route and redirect the `/` to `/app`, this will allow us to use the `/` as the project home page later.

Add `/app` route and redirect `/` to `/app`

---

package-lock.json
package.json
src/components/layers/ItkVtkLayer.vue
src/components/layers/VectorLayer.vue

This PR aims to fix the bug when no data is passed to the vector layer.

Fix empty data error

---

package-lock.json
package.json
src/components/ImageViewer.vue
src/components/layers/VectorLayer.vue

Small fix for dragging layer order on mobile and change the tooltip position.

Improve drag delay and tooltip position

---

src/components/ImageViewer.vue
src/components/layers/ImageLayer.vue
src/components/layers/ItkVtkLayer.vue
src/components/layers/VectorLayer.vue

This PR enables loading files as layers.

Support loading local files as layers

---

package-lock.json
package.json
src/components/ImageViewer.vue
src/components/layers/ImageLayer.vue
src/components/layers/ItkVtkLayer.vue
src/views/About.vue

This PR add initial screenshot support, notice that it's not working with itk-vtk layer yet.
The undefined name issue reported by @muellerflorian  is fixed in this PR.

Support taking screenshot

---

package-lock.json
package.json
src/components/layers/ItkVtkLayer.vue
src/components/layers/VectorLayer.vue
src/imjoyAPI.js

This PR support passing np.array directly to the vector layer (without `tolist()`).
`add_points` now support `edge_color`, `edge_width` and `face_color`
@muellerflorian

Support loading ndarray to vector layer and fix point style

---

README.md
package-lock.json
package.json
src/imjoyAPI.js

This PR allows pass an array of numpy array for vector layers and also improves the example in README.

Convert ndarray recursively and improve readme

---

README.md

Added a small tutorial for binder: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gist/oeway/690c2e62311223ae93e644d542eb8949/master?filepath=Kaibu-jupyter-tutorial.ipynb)
Source code here: https://gist.github.com/oeway/690c2e62311223ae93e644d542eb8949

Improve binder URL

---

package-lock.json
package.json
src/components/ImageViewer.vue
src/store.js

This is a fix to the "failed to add layer" error for itk-vtk-layer.

Fix add layer error

---

package-lock.json
package.json
src/components/ImageViewer.vue
src/components/layers/VectorLayer.vue
src/components/widgets/TreeWidget.vue
src/components/widgets/Vega.vue
src/components/widgets/VegaWidget.vue
src/components/widgets/index.js
src/components/widgets/sl-vue-tree-light.css

The `tree` widgets allows displaying a hirachical file/object tree:
Example code in Python:
```python
viewer = await api.createWindow(src="https://kaibu.org/#/app")
async def node_dbclick_callback(node):
api.alert('node double clicked: ' + str(node))
tree = await viewer.add_widget(
{
"_rintf": True,
"type": "tree",
"name": "Files",
"node_dbclick_callback": node_dbclick_callback,
"nodes": [{
"title": "Item2",
"isLeaf": True,
"data": {"visible": False},
"isSelected": False,
}],
}
)
await tree.clear_nodes()
await tree.set_nodes(
[
{"title": "Item1", "isLeaf": True, "isSelected": False},
{
"title": "Item2",
"isLeaf": True,
"data": {"visible": False},
"isSelected": False,
},
{
"title": "Folder1",
"children": [
{"title": "Item4", "isLeaf": True, "isSelected": False},
{"title": "Item3", …
```

Support tree widget

---

package-lock.json
package.json
src/components/layers/VectorLayer.vue

This is a useful feature when we want to correct polygon produced, e.g. from a deep learning algorithm.

Support cutting polygons

---

package-lock.json
package.json
src/components/layers/ItkVtkLayer.vue

Fixes https://github.com/imjoy-team/kaibu/issues/31
@muellerflorian

Fix setVisible bug for itk-vtk-layer

---

package-lock.json
package.json
src/components/layers/VectorLayer.vue

The modify interaction make the interface laggy when displaying more polygons, this PR removes it to allow better performance.

Disable modify to improve performance

---

package-lock.json
package.json
src/components/layers/ItkVtkLayer.vue

When using itk-vtk-layer with annotation on a touch screen device, the underlaying image jitters.

Fix itk-vtk-layer jittering on touchscreen

---

docs/api.md
package-lock.json
package.json
src/components/ImageViewer.vue
src/components/layers/VectorLayer.vue
src/components/widgets/ControlWidget.vue

This PR add events for handling feature add/remove/change/select, and improve the docs to add missing returned layer api functions.

Add vector events and improve docs

---

package-lock.json
package.json
src/components/layers/VectorLayer.vue

This PR adds two buttons for mobile devices: delete and undo.

Add delete and undo buttons

---

docs/api.md

Add skin image annotation example

---

docs/api.md
package-lock.json
package.json
src/components/ImageViewer.vue
src/components/layers/VectorLayer.vue
src/store.js

This PR supports displaying tags/comments and allows attach a widget to a layer

Support displaying feature metadata and attaching widget to a layer

---

CHANGELOG.md
src/components/ImageViewer.vue

Don't show sidebar as overlay

---

docs/api.md
package-lock.json
package.json
src/components/layers/VectorLayer.vue

This PR add an option to the annotation layer to enable select during initialization.

Add select_enable

---

src/components/layers/VectorLayer.vue

Provide a way to obtain the currently selected object through an API.

add get_selected_features to vector layer API
